---

- name: installing and lauching metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: download metricbeta deb
    command: curl -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: install metricbeat deb
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: drop in metricbeat.yml
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure docker module
    command: metricbeat modules enable docker

  - name: setup metricbeat
    command: metricbeat setup

- name: enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes
